/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BookPayment } from "./BookPayment";
export * as factories from "./factories";
export { BookPayment__factory } from "./factories/BookPayment__factory";
